### ISSUE TITLE
How do I make the titlebar respect Nords color?

### ISSUE THREAD

**Issue by KTsarlz** [arcticicestudio/nord-iterm2#5]
I can't seem to see a way around this. I'm new to iterm2 though so I may not just see.

**Comment by arcticicestudio** [comment]
The theme format itself does not provide a way to change the title bar to a custom color, but the official documentation about [Proprietary Escape Codes](https://iterm2.com/documentation-escape-codes.html) contains a section on how to "*Set window title and tab chrome background color*".

These escape codes allow to modify the title bar and tab background color by passing a RGB value where `N` is a number in `0` and `255`:

```
^[]6;1;bg;red;brightness;N^G
^[]6;1;bg;green;brightness;N^G
^[]6;1;bg;blue;brightness;N^G
```

If you want the title bar to match Nord you can pass the RGB value for `nord0` (`46, 52, 64`). Add these commands to your terminals initialization file like `.bashrc` or `.zshrc` to automatically apply the title bar style for new sessions:

```sh
echo -e "\033]6;1;bg;red;brightness;46\a"
echo -e "\033]6;1;bg;green;brightness;52\a"
echo -e "\033]6;1;bg;blue;brightness;64\a"
```

Some other references I've found are [a blog entry](https://codematters.blog/custom-iterm2-titlebar-background-colors-a088c6f2ec60) and [this discussion on the official GitLab iTerm2 repository](https://gitlab.com/gnachman/iterm2/issues/4080).

@KTsarlz Please let me know if it worked fou you so I can add this to the project documentation as reference for other users :smile:

**Comment by KTsarlz** [comment]
I have tried that but doesn't work.. I also saw this on medium iirc. :/ 
<img width="762" alt="screen shot 2017-10-02 at 17 53 26" src="https://user-images.githubusercontent.com/9140507/31072496-bfb602ac-a79a-11e7-86ec-375cd93894fa.png">

**Comment by arcticicestudio** [comment]
Are you running on High Sierra?
The iTerm2 maintainer says that it [actually makes it impossible to change title bar color](https://gitlab.com/gnachman/iterm2/issues/4080#note_35667605) on Sierra.

**Comment by KTsarlz** [comment]
I'm on High Sierra :/ Thanks for linking this. I'll try this later when I get home

**Comment by arcticicestudio** [comment]
@KTsarlz I've checked the linked issue comments again and everyone confirms that it is not possible to get this running on High Sierra. I'll close this for now, maybe it will be working again in some future updates so we can reopen this issue again and see if it is possible to integrate it into the theme or at least document how to apply it manually.
